replicaCount: 2

image:
  repository: ghcr.io/rusudinu/hello-kub
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: "hello-kub-redirect-https@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  hosts:
    - host: hello-kub.rusudinu.ro
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: hello-kub-tls
      hosts:
        - hello-kub.rusudinu.ro

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 40
  targetMemoryUtilizationPercentage: 40

nodeSelector: {}
tolerations: []
affinity: {}
