replicaCount: 2

image:
  repository: ghcr.io/rusudinu/hello-kub
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: hello-world.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
